---
- name: Reposync on the host
  hosts: localhost
  tasks:
    - name: install rhos-release
      yum:
        name: http://download.lab.bos.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
        state: present

    - name: show the puddle_id value
      debug:
        msg: "Puddle ID {{ puddle_id }}"
      when: puddle_id is defined
    
    - name: Run rhos-release with the puddle
      command: rhos-release 12 -p {{ puddle_id }}

    - name: make the puddle dir
      file: 
        path: /var/www/html/{{ item }}
        state: directory
      with_items:
        rhelosp-12.0-puddle
        rhelosp-rhel-7.4-extras
        rhelosp-rhel-7.4-ha
        rhelosp-rhel-7.4-server

    - name: run the reposync
      command: reposync -r {{ item }} -n -p /var/www/html/puddle/{{ item }}
      with_items:
        rhelosp-12.0-puddle
        rhelosp-rhel-7.4-extras
        rhelosp-rhel-7.4-ha
        rhelosp-rhel-7.4-server

    - name: run create repo on the puddle
      command: createrepo -o puddle puddle
      args:
        chdir: /var/www/html/

    - name: create the http dir fro repomod
      file:
        path: /var/www/html/{{ puddle_id }}
        state: directory


